services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./logs:/var/log/modular-sharding:ro
      - ./data/alloy/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - ALLOY_ENV=prod

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./data/loki/data:/loki
      - ./data/loki/loki-config.yaml:/etc/loki/local-config.yaml
    environment:
      TZ: "Asia/Seoul"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      TZ: "Asia/Seoul"
      GF_SERVER_ROOT_URL: "http://0.0.0.0:3000/grafana/"
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ENABLE_GZIP: "true"
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    command:
      - --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:
