spring:
  application:
    name: demo

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
        default_batch_fetch_size: 100

  datasource:
    url: jdbc:postgresql://localhost:5432/demo_application
    username: history_shard_1
    password: demo1234

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

datasource:
  history:
    mode: SINGLE # or SHARD

    shard:
      strategy: MODULAR
      mod: 2

    single:
        username: history_shard_1
        url: jdbc:postgresql://localhost:5432/demo_shard_1
        password: demo1234

    shards:
      - username: history_shard_1
        password: demo1234
        master:
          name: master-history-1
          url: jdbc:postgresql://localhost:5432/demo_shard_1
      - username: history_shard_1
        password: demo1234
        master:
          name: master-history-2
          url: jdbc:postgresql://localhost:5432/demo_shard_2

sharding:
  mode: template # or aop
  history:
    strategy: MODULAR
    mod: 2