spring:
  application:
    name: demo

  profiles:
    default: default

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
        default_batch_fetch_size: 100

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo_application}
    username: ${SPRING_DATASOURCE_USERNAME:history_shard_1}
    password: ${SPRING_DATASOURCE_PASSWORD:demo1234}

management:
  otlp:
    metrics:
      export:
        enabled: false

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

datasource:
  history:
    mode: SINGLE # or SHARDED

    shard:
      strategy: MODULAR
      mod: 2

    single:
        username: ${HISTORY_DB_USERNAME:history_shard_1}
        url: ${HISTORY_DB_URL:jdbc:postgresql://localhost:5432/demo_shard_1}
        password: ${HISTORY_DB_PASSWORD:demo1234}

    shards:
      - username: history_shard_1
        password: demo1234
        master:
          name: master-history-1
          url: jdbc:postgresql://localhost:5432/demo_shard_1
      - username: history_shard_1
        password: demo1234
        master:
          name: master-history-2
          url: jdbc:postgresql://localhost:5432/demo_shard_2

sharding:
  mode: template # or aop

logging:
  file:
    path: ./logs

  structured:
    format:
      file: logstash